### ISSUE TITLE
Add native OpenDAL support

### ISSUE THREAD

**Issue by WenyXu** [datafusion-contrib/datafusion-orc#116]
Add native OpenDAL support for ORC
See also: https://github.com/apache/opendal/issues/4962

**Comment by Xuanwo** [comment]
It should be super simple to implement an `AsyncChunkReader` for opendal. I will give it a try.

**Comment by WenyXu** [comment]
> It should be super simple to implement an `AsyncChunkReader` for opendal. I will give it a try.

Have fun 🤩

**Comment by Xuanwo** [comment]
Hi, I didn't find `AsyncWrite` for orc. Seems we doesn't support write orc files yet?

**Comment by WenyXu** [comment]
> Hi, I didn't find `AsyncWrite` for orc. Seems we doesn't support write orc files yet?

Yes, the feature still WIP #11

**Comment by Xuanwo** [comment]
Thanks! We can add `AsyncOpendalWriter` once it's ready.

**Comment by Xuanwo** [comment]
Implemented in https://github.com/datafusion-contrib/datafusion-orc/pull/117
