### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by Jefffrey** [datafusion-contrib/datafusion-orc#129]
Made a mistake in publishing 0.4.0 where didn't publish with all features, meaning docs relating to `datafusion` feature are not present on https://docs.rs/orc-rust/0.4.0/orc_rust/

Do a 0.4.1 release to fix this

**Comment by Xuanwo** [comment]
Hi, I believe it's not related to publishing. We should configure the docs.rs build feature. Refer to this: https://docs.rs/about/metadata

**Comment by Jefffrey** [comment]
Published: https://github.com/datafusion-contrib/datafusion-orc/releases/tag/v0.4.1

docs seems fixed now:

![image](https://github.com/user-attachments/assets/93fbb7a4-d2e9-44f2-a9e1-3d047e919839)
