### ISSUE TITLE
Requires nightly to compile

### ISSUE THREAD

**Issue by Jefffrey** [datafusion-contrib/datafusion-orc#2]
Seems we currently rely on some unstable features, wondering if we should continue as such and require nightly or change to stable to be similar to arrow-rs?

**Comment by Jefffrey** [comment]
@WenyXu  @waynexia

**Comment by WenyXu** [comment]
> Seems we currently rely on some unstable features, wondering if we should continue as such and require nightly or change to stable to be similar to arrow-rs?

Hi @Jefffrey, We only use the `iterator_try_collect` feature, and I submitted a PR to remove these unstable features, PTAL.
