### ISSUE TITLE
Consider switching to trunk based workflow?

### ISSUE THREAD

**Issue by Jefffrey** [datafusion-contrib/datafusion-orc#55]
First of all, sorry for the slow progress, I do still intend to work on this but have just been juggling other items at the moment.

I was considering making the workflow of this repo more trunk based, where those with write access can just push direct to main without requiring a PR and approval.

Benefits:

- small set of contributors at the moment, so avoid overhead of requiring PR for every change
- this project doesn't need to worry about stability at the moment, so can move faster

Thoughts? @waynexia @WenyXu

**Comment by WenyXu** [comment]
I'm totally fine about this idea. BTW, maybe we can consider to release some stable version periodically in the future?

**Comment by waynexia** [comment]
+1 for this. The only thing is we still need to make sure the quality of direct commits (like test and CI are passed).

>BTW, maybe we can consider to release some stable version periodically in the future?

What do you think of release one recently as there are already some big changes and features?

**Comment by Jefffrey** [comment]
Thanks for the response, I'll tweak the repository settings to try allow this.

Regarding release, I don't have much experience with publishing crates so I'll defer to your experiences, but I'm not opposed to occasional releases. Would it still fall under https://crates.io/crates/orc-rust or a separate one?

**Comment by WenyXu** [comment]
> Would it still fall under https://crates.io/crates/orc-rust or a separate one?

I'm unsure about this since we changed the package name in the `Cargo.toml`. I will do some surveys to figure out it. BTW, @waynexia Do you have any ideas?

**Comment by Jefffrey** [comment]
Pushing to main enabled, will try keep commits small where possible
