### ISSUE TITLE
Release strategy 

### ISSUE THREAD

**Issue by Jefffrey** [datafusion-contrib/datafusion-orc#61]
Brought up in #55

Determine release cadence with process, etc.

**Comment by Jefffrey** [comment]
For reference: https://crates.io/crates/orc-rust

**Comment by Jefffrey** [comment]
Should be included as part of https://github.com/datafusion-contrib/datafusion-orc/issues/71 as well

**Comment by Jefffrey** [comment]
I'm gonna pick this up now, to try focus on cleaning up the documentation & processes a bit (as part of https://github.com/datafusion-contrib/datafusion-orc/issues/71)

@WenyXu @waynexia do you have any thoughts on reusing the existing https://crates.io/crates/orc-rust crate or would prefer a new one? If reusing the existing one, we can publish a new version `0.3.0` after I update some of the documentation a bit more.

**Comment by WenyXu** [comment]
> I'm gonna pick this up now, to try focus on cleaning up the documentation & processes a bit (as part of #71)
> 
> @WenyXu @waynexia do you have any thoughts on reusing the existing https://crates.io/crates/orc-rust crate or would prefer a new one? If reusing the existing one, we can publish a new version `0.3.0` after I update some of the documentation a bit more.

I'm okay with both options. If you decide to reuse the existing one, I will add you to the owner team.

**Comment by Jefffrey** [comment]
I think we can reuse the existing crate, to avoid needing to create a new crate. I'll adjust the metadata in Cargo.toml accordingly.

**Comment by WenyXu** [comment]
> I think we can reuse the existing crate, to avoid needing to create a new crate. I'll adjust the metadata in Cargo.toml accordingly.

Great. I have invited you to join the owner team. You will receive an email shortly.
