### ISSUE TITLE
Do you have a plan for ORC writer?

### ISSUE THREAD

**Issue by qianyiwen2019** [datafusion-contrib/datafusion-orc#89]
Thanks for your excellent work.
And do you have a pan for a writer? it's also useful in many cases.

**Comment by WenyXu** [comment]
Thank you for your appreciation of our work.

Regarding your inquiry about a writer feature, while it's certainly a valuable addition, we currently lack the resources to implement it. However, we warmly welcome any contributions in this regard. Notably, ORC Writer boasts implementations in various other languages, making the creation of a Rust version relatively straightforward. Additionally, leveraging GPT for code translation could streamline the process.

---

**Comment by qianyiwen2019** [comment]
got it, thanks

**Comment by Jefffrey** [comment]
I am actually planning to do an implementation of writing (it will be rudimentary and unoptimized at first). We have an existing issue for this where I might post progress as it comes: https://github.com/datafusion-contrib/datafusion-orc/issues/11

**Comment by qianyiwen2019** [comment]
> I am actually planning to do an implementation of writing (it will be rudimentary and unoptimized at first). We have an existing issue for this where I might post progress as it comes: #11

wonderful, hope we can see it sooner.
